name: cloud_cost_analyzer

services:
  postgres:
    image: postgres
    container_name: cloud_cost_analyzer-postgres
    environment:
      POSTGRES_DB: cloudcost
      POSTGRES_USER: cloudcost
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cloud_cost_analyzer_postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cloudcost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  cloud_cost_analyzer_postgres_data:
